name: Keep Render Awake

on:
  schedule:
    - cron: '*/12 * * * *'   # هر ۳ دقیقه یکبار
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request to Keep Service Alive
        run: |
          RENDER_SERVICE_URL="https://mvpnbot-3.onrender.com"
          echo "Pinging ${RENDER_SERVICE_URL}..."
          curl -s -o /dev/null "${RENDER_SERVICE_URL}"
          echo "Ping successful at $(date)"
